---
services:
    php:
        build:
            context: ./php/${PHP_VERSION}
            args:
                XDEBUG_VERSION: ${XDEBUG_VERSION:-3.0.0}
                XDEBUG_MODE: ${XDEBUG_MODE:-off}
                COMPOSER_VERSION: ${COMPOSER_VERSION:-latest}
        container_name: ${COMPOSE_PROJECT_NAME}_php
        volumes_from:
            - source
        links:
            - db
            - memcached
        environment:
            TZ: Europe/Moscow
            XDEBUG_CONFIG: "discover_client_host=${XDEBUG_DISCOVER_CLIENT_HOST:-false} client_host=${XDEBUG_HOST:-host.docker.internal} start_with_request=${XDEBUG_START_WITH_REQUEST:-default} remote_host=${XDEBUG_HOST:-host.docker.internal} remote_port=${XDEBUG_PORT:-9001} remote_enable=${XDEBUG_REMOTE_ENABLE:-0} default_enable=${XDEBUG_REMOTE_ENABLE:-0} remote_autostart=${XDEBUG_REMOTE_ENABLE:-0} remote_connect_back=${XDEBUG_CONNECT_BACK:-0}"
        stdin_open: true
        tty: true
        networks:
            - booking
        ports:
            - "${INTERFACE:-127.0.0.1}:${PHP_FPM_PORT:-9000}:9000"
            - "${INTERFACE:-127.0.0.1}:${PHP_SSH_PORT:-22}:22"
        restart: unless-stopped

    web_server:
        build: ./${WEB_SERVER_TYPE}
        container_name: ${COMPOSE_PROJECT_NAME}_web_server
        depends_on:
            - source
        volumes_from:
            - source
        ports:
            - "${INTERFACE:-127.0.0.1}:80:80"
            - "${INTERFACE:-127.0.0.1}:443:443"
        links:
            - php
        networks:
            - booking
        environment:
            TZ: Europe/Moscow
        stdin_open: true
        tty: true
        restart: unless-stopped

    db:
        build: ./${DB_SERVER_TYPE}
        container_name: ${COMPOSE_PROJECT_NAME}_db
        volumes:
            - ./${DB_SERVER_TYPE}/init:/docker-entrypoint-initdb.d
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:3306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            TZ: Europe/Moscow
        command: mysqld --user=root --sql-mode=""
        networks:
            - booking
        stdin_open: true
        tty: true
        restart: unless-stopped

    memcached:
        image: memcached:latest
        container_name: ${COMPOSE_PROJECT_NAME}_memcached
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:11211:11211'
        networks:
            - booking
        environment:
            TZ: Europe/Moscow
        stdin_open: true
        tty: true
        restart: unless-stopped

    adminer:
        image: dockette/adminer:full
        container_name: ${COMPOSE_PROJECT_NAME}_adminer
        links:
            - db:db
        ports:
            - '${INTERFACE}:8080:80'
        environment:
            UPLOAD: 1024M # upload_max_filesize, post_max_size
            TZ: Europe/Moscow
        restart: unless-stopped
        stdin_open: true
        tty: true
        networks:
            - booking

    source:
        image: alpine:latest
        container_name: ${COMPOSE_PROJECT_NAME}_source
        volumes:
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ./logs/php:/var/log/php
            - ./logs/db:/var/log/mysql
            - ./logs/memcached:/var/log/memcached
            - db:/var/lib/mysql
            - cache:/var/lib/memcached
            - ${SITE_PATH}:/var/www
            - /etc/localtime:/etc/localtime/:ro
        networks:
            - booking

volumes:
    db:
        driver: local
    cache:
        driver: local

networks:
    booking:
        external: false
